spring.application.name=DigitalRepositoryBackend
spring.datasource.url=jdbc:mysql://192.168.1.246:3306/srinidhiVDR
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.format_sql=true
hibernate.cache.auto_evict_collection_cache=true
#server.port=8082 Sripathi sripathiTesting  SrinidhiDigitalRepo
# hibernate properties
#server.port = 8085

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false

jwt.secret=javainuse
##logging.level.org.apache.tomcat=DEBUG

##logging.level.org.apache.catalina=DEBUG

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.context=DEBUG

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration

spring.groovy.template.enabled=false
spring.groovy.template.check-template-location=false



##################

# smtp-mail.mail.srinidhicredit.in

##################
#spring.mail.host=mail.srinidhicredit.in
#spring.mail.port=587
#spring.mail.username=it@srinidhicredit.in
#spring.mail.password=Rytways#8374
#spring.mail.properties.mail.protocol=smtp
#spring.mail.properties.mail.tls=true
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=mail.srinidhicredit.in

################################
spring.mail.host=mail.sripathi.net
spring.mail.port=587
spring.mail.username=apps@sripathi.net
spring.mail.password=Apps@dmin123
spring.mail.properties.mail.protocol=smtp
spring.mail.properties.mail.tls=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=mail.sripathi.net


# SSL, port 465
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory

## Jasper Report Properties smb://192.168.1.71/commonshare/arul/pugal/VJP/src/main/resources/templates

## net.sf.jasperreports.extension.registry.factory.fonts=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
## net.sf.jasperreports.extension.simple.font.families.ireport=irfonts.xml


## Configure Multipart File for Servlet

#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

#Comment by Lokesh
#file.upload.directory=/downloads/downloads/SRIPATHI/Input
#
#companyImageFilePath=/filedir/pugal/templates/Sripathi.PNG
#
##jrxmlfilePathToInputSheetpm1=/home/sakthik/WorkSpace/EclipseWorkSpace/SRIPATHI/src/main/resources/templates/DuplexPricePm1.jrxml
##jrxmlfilePathToInputSheetpm2=/home/sakthik/WorkSpace/EclipseWorkSpace/SRIPATHI/src/main/resources/templates/MainReport.jrxml
##jrxmlfilePathToInputSheetpm3=/home/sakthik/WorkSpace/EclipseWorkSpace/SRIPATHI/src/main/resources/templates/DuplexPricePm3
##jrxmlfilePathToInputSheetpm4=/home/sakthik/WorkSpace/EclipseWorkSpace/SRIPATHI/src/main/resources/templates/DuplexPricePm4
##jrxmlfilePathToInputSheetpm5=/home/sakthik/WorkSpace/EclipseWorkSpace/SRIPATHI/src/main/resources/templates/DuplexPricePm5
#
#
#jrxmlfilePathToInputSheetpm1=/filedir/pugal/templates/Sripathi/DuplexPricePm1.jrxml
#jrxmlfilePathToInputSheetpm2=/filedir/pugal/templates/Sripathi/MainReport.jrxml
#jrxmlfilePathToInputSheetpm3=/filedir/pugal/templates/Sripathi/DuplexPricePm3.jrxml
#jrxmlfilePathToInputSheetpm4=/filedir/pugal/templates/Sripathi/DuplexPricePm4.jrxml
#jrxmlfilePathToInputSheetpm5=/filedir/pugal/templates/Sripathi/DuplexPricePm5.jrxml
#jrxmlfilePathToInputSheetpm6=/filedir/pugal/templates/Sripathi/ExportProductPrice.jrxml
#jrxmlfilePathPalTransaction=/filedir/pugal/templates/Sripathi/PalletTransacReport.jrxml
#jrxmlfilePathPalletCheckOut=/filedir/pugal/templates/Sripathi/PalletCheckOutReport.jrxml
#jrxmlfilePathRealTransaction=/filedir/pugal/templates/Sripathi/RealTransacReport.jrxml
#jrxmlfilePathRealCheckOutReport=/filedir/pugal/templates/Sripathi/RealCheckOutReport.jrxml
#
#upload.path =/filedir/RytwaysDigitalRepo/
#
##pathofpdfReport=/home/sakthik
## Migration
#jrxmlfilePathmaterial1=/filedir/pugal/templates/MaterialRequest/VJP_MaterialFile.jrxml
#pathofMaterialpdfReport=/downloads/downloads/Srinidhi/Generated/
#
#pathofpdfReport=/downloads/downloads/SRIPATHI/REPORTS
#pathofPalletTrasnsacpdfReport=/downloads/downloads/SRIPATHI/PalletTransacReports
#pathofrealTrasnsacpdfReport=/downloads/downloads/SRIPATHI/RealTransacReports

docReportUploadPath=/filedir/SrinidhiDigitalRepo/
#digitReportExcelUploadPath=Digital repository/excelDownloads/Document/
#
## Migration 
#pathofInvoiceExcelReport =/downloads/downloads/Srinidhi/excelDownloads/Invoice/
#pathofPurchaseExcelReport =/downloads/downloads/Srinidhi/excelDownloads/PurchaseDownloads/
#
##server.servlet.context-path=/SRIPATHICLIENT;
##server.servlet.context-path=/SRIPATHICLIENT;
